export const THREAD_DETAIL_ACTION_TYPES = {
  RECEIVE_THREAD_DETAIL: 'threadDetail/RECEIVE_THREAD_DETAIL',
  CLEAR_THREAD_DETAIL: 'threadDetail/CLEAR_THREAD_DETAIL',
  ADD_COMMENT_THREAD_DETAIL: 'threadDetail/ADD_COMMENT_THREAD_DETAIL',
  TOGGLE_UPVOTE_THREAD_DETAIL: 'threadDetail/TOGGLE_UPVOTE_THREAD_DETAIL',
  TOGGLE_NEUTRALVOTE_THREAD_DETAIL: 'threadDetail/TOGGLE_NEUTRALVOTE_THREAD_DETAIL',
  TOGGLE_DOWNVOTE_THREAD_DETAIL: 'threadDetail/TOGGLE_DOWNVOTE_THREAD_DETAIL',
  TOGGLE_UPVOTE_COMMENT_THREAD_DETAIL: 'threadDetail/TOGGLE_UPVOTE_COMMENT_THREAD_DETAIL',
  TOGGLE_NEUTRALVOTE_COMMENT_THREAD_DETAIL: 'threadDetail/TOGGLE_NEUTRALVOTE_COMMENT_THREAD_DETAIL',
  TOGGLE_DOWNVOTE_COMMENT_THREAD_DETAIL: 'threadDetail/TOGGLE_DOWNVOTE_COMMENT_THREAD_DETAIL',
};
