export const THREADS_ACTION_TYPES = {
  RECEIVE_THREADS: 'threads/RECEIVE_THREADS',
  ADD_THREAD: 'threads/ADD_THREAD',
  TOGGLE_UPVOTE_THREAD: 'threads/TOGGLE_UPVOTE_THREAD',
  TOGGLE_NEUTRALVOTE_THREAD: 'threads/TOGGLE_NEUTRALVOTE_THREAD',
  TOGGLE_DOWNVOTE_THREAD: 'threads/TOGGLE_DOWNVOTE_THREAD',
};
